DELETE FROM SYNONYMS;
INSERT INTO SYNONYMS (left,right, language) VALUES ('Altenmunster','Altenmünster', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Biere','Bière', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('#bil','Barleywine', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Brau','Bräu', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Burgerbrau','Bürgerbräu', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Dollnitzer','Döllnitzer', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Dusseldorf','Düsseldorf', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Fruh','Früh', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Fuchschen','Füchschen', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Gratzer','Grätzer', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Hazy IPA','New England IPA', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Hefeweizen','Weissbier', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Kolsch','Kölsch', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Koln','Köln', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Konig','König', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Kostritzer','Köstritzer', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Lowenbrau','Löwenbraü', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Marzen','Märzen', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Monchshof','Mönchshof', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Muhlen','Mühlen', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Munchner','Münchner', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Naturtrub','Naturtrüb', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('New England IPA','New England IPA', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Octoberfest','Märzen', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Oktoberfest','Märzen', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Schlosser','Schlösser', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Schlussel','Schlüssel', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Schonramer','Schönramer', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Sunner','Sünner', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Troegs','Tröegs', 'en');

--Spanish
INSERT INTO SYNONYMS (left,right, language) VALUES ('Acidas','Ácidas', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Altenmunster','Altenmünster', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Ambar','Ámbar', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Baltica','Báltica', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Biere','Bière', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('#bil','Barleywine', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Brau','Bräu', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Britanicas','Británicas', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Burgerbrau','Bürgerbräu', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Clasico','Clásico', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Comun','Común', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Dollnitzer','Döllnitzer', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Dusseldorf','Düsseldorf', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('esta','está', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Estandar','Estándar', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Estandares','Estándares', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Exportacion','Exportación', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Fermentacion','Fermentación', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Fruh','Früh', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Fuchschen','Füchschen', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Gratzer','Grätzer', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Guia','Guía', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Hefeweizen','Weissbier', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Historica','Histórica', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Ingles','Inglés', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Introduccion','Introducción', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('IPA Brumoso','IPA Nueva Inglaterra', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('IPA Ingles','IPA Inglés', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('IPA Nueva Inglaterra','IPA Nueva Inglaterra', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Koln','Köln', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Kolsch','Kölsch', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Konig','König', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Kostritzer','Köstritzer', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Lowenbrau','Löwenbraü', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Marron','Marrón', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Marzen','Märzen', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Monchshof','Mönchshof', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Muhlen','Mühlen', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Munchner','Münchner', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Naturtrub','Naturtrüb', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Octoberfest','Märzen', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Oktoberfest','Märzen', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Palida','Pálida', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Pre-Prohibicion','Pre-Prohibición', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Prohibicion','Prohibición', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Schlosser','Schlösser', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Schlussel','Schlüssel', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Schonramer','Schönramer', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Sunner','Sünner', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Troegs','Tröegs', 'es');