DELETE FROM SYNONYMS;
INSERT INTO SYNONYMS (left,right, language) VALUES ('#bil','Barleywine', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('#bil','Barleywine', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Hazy IPA','New England IPA', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('IPA Brumoso','IPA Nueva Inglaterra', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Hefeweizen','Weissbier', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Hefeweizen','Weissbier', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('New England IPA','New England IPA', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('IPA Nueva Inglaterra','IPA Nueva Inglaterra', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Octoberfest','Märzen', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Octoberfest','Märzen', 'es');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Oktoberfest','Märzen', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Oktoberfest','Märzen', 'es');