INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Altenmunster','Altenmünster', 'en','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Biere','Bière', 'en','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('#bil','Barleywine', 'en','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Brau','Bräu', 'en','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Burgerbrau','Bürgerbräu', 'en','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Dollnitzer','Döllnitzer', 'en','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Dusseldorf','Düsseldorf', 'en','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Fruh','Früh', 'en','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Fuchschen','Füchschen', 'en','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Gratzer','Grätzer', 'en','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Hazy IPA','New England IPA', 'en','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Hefeweizen','Weissbier', 'en','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Kolsch','Kölsch', 'en','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Koln','Köln', 'en','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Konig','König', 'en','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Kostritzer','Köstritzer', 'en','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Lowenbrau','Löwenbraü', 'en','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Marzen','Märzen', 'en','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Monchshof','Mönchshof', 'en','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Muhlen','Mühlen', 'en','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Munchner','Münchner', 'en','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Naturtrub','Naturtrüb', 'en','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('New England IPA','New England IPA', 'en','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Octoberfest','Märzen', 'en','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Oktoberfest','Märzen', 'en','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Schlosser','Schlösser', 'en','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Schlussel','Schlüssel', 'en','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Schonramer','Schönramer', 'en','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Sunner','Sünner', 'en','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Troegs','Tröegs', 'en','BJCP_2015');

-- BJCP 2021 English
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Altenmunster','Altenmünster', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Biere','Bière', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('#bil','Barleywine', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Brau','Bräu', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Burgerbrau','Bürgerbräu', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Dollnitzer','Döllnitzer', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Dusseldorf','Düsseldorf', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Fruh','Früh', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Fuchschen','Füchschen', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Gratzer','Grätzer', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Hefeweizen','Weissbier', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Kolsch','Kölsch', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Koln','Köln', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Konig','König', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Kostritzer','Köstritzer', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Lowenbrau','Löwenbraü', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Marzen','Märzen', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Monchshof','Mönchshof', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Muhlen','Mühlen', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Munchner','Münchner', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Naturtrub','Naturtrüb', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('New England IPA','New England IPA', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Octoberfest','Märzen', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Oktoberfest','Märzen', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Schlosser','Schlösser', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Schlussel','Schlüssel', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Schonramer','Schönramer', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Sunner','Sünner', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Troegs','Tröegs', 'en','BJCP_2021');

--Spanish
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Acidas','Ácidas', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Altenmunster','Altenmünster', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Ambar','Ámbar', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('américa-del-norte','america-del-norte', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Baltica','Báltica', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Biere','Bière', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('#bil','Barleywine', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Brau','Bräu', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Britanicas','Británicas', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Burgerbrau','Bürgerbräu', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Clasico','Clásico', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Comun','Común', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Dollnitzer','Döllnitzer', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Dusseldorf','Düsseldorf', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('esta','está', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Estandar','Estándar', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Estandares','Estándares', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Exportacion','Exportación', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Fermentacion','Fermentación', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Fruh','Früh', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Fuchschen','Füchschen', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Gratzer','Grätzer', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Guia','Guía', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Hazy IPA','New England IPA', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Hefeweizen','Weissbier', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Historica','Histórica', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Ingles','Inglés', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Introduccion','Introducción', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Koln','Köln', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Kolsch','Kölsch', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Konig','König', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Kostritzer','Köstritzer', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Lowenbrau','Löwenbraü', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Marron','Marrón', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Marzen','Märzen', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Monchshof','Mönchshof', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Muhlen','Mühlen', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Munchner','Münchner', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Naturtrub','Naturtrüb', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('New England IPA','New England IPA', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Octoberfest','Märzen', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Oktoberfest','Märzen', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Palida','Pálida', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Schlosser','Schlösser', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Schlussel','Schlüssel', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Schonramer','Schönramer', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Sunner','Sünner', 'es','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Troegs','Tröegs', 'es','BJCP_2015');

-- BJCP 2015 Ukrainian
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Altenmunster','Altenmünster', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Biere','Bière', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('#bil','Barleywine', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Brau','Bräu', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Burgerbrau','Bürgerbräu', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Dollnitzer','Döllnitzer', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Dusseldorf','Düsseldorf', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Fruh','Früh', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Fuchschen','Füchschen', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Gratzer','Grätzer', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Hazy IPA','New England IPA', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Hefeweizen','Weissbier', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Koln','Köln', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Kolsch','Kölsch', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Konig','König', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Kostritzer','Köstritzer', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Lowenbrau','Löwenbraü', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Marzen','Märzen', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Monchshof','Mönchshof', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Muhlen','Mühlen', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Munchner','Münchner', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Naturtrub','Naturtrüb', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('New England IPA','New England IPA', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Octoberfest','Märzen', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Oktoberfest','Märzen', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Schlosser','Schlösser', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Schlussel','Schlüssel', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Schonramer','Schönramer', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Sunner','Sünner', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Troegs','Tröegs', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('ІПА','IPA', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('ІРА','IPA', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Браун','Brown', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Гозе','Gose', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Дабл','Double', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Дюбель','Dubbel', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Копчений','Smoked', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Коричневий','Brown', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Кьольш','Kölsch', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Оуд','Oud', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Сайзон','Saison', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Сейзон','Saison', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Трипель','Tripel', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Тріпель','Tripel', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Хез','Gueuze', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Янтарний','Amber', 'uk','BJCP_2015');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Ячмінне вино','Barleywine', 'uk','BJCP_2015');

-- BJCP 2021 Ukrainian
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Altenmunster','Altenmünster', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Biere','Bière', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('#bil','Barleywine', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Brau','Bräu', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Burgerbrau','Bürgerbräu', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Dollnitzer','Döllnitzer', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Dusseldorf','Düsseldorf', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Fruh','Früh', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Fuchschen','Füchschen', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Gratzer','Grätzer', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Hazy IPA','New England IPA', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Hefeweizen','Weissbier', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Koln','Köln', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Kolsch','Kölsch', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Konig','König', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Kostritzer','Köstritzer', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Lowenbrau','Löwenbraü', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Marzen','Märzen', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Monchshof','Mönchshof', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Muhlen','Mühlen', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Munchner','Münchner', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Naturtrub','Naturtrüb', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('New England IPA','New England IPA', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Octoberfest','Märzen', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Oktoberfest','Märzen', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Schlosser','Schlösser', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Schlussel','Schlüssel', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Schonramer','Schönramer', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Sunner','Sünner', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Troegs','Tröegs', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('ІПА','IPA', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('ІРА','IPA', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Браун','Brown', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Гозе','Gose', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Дабл','Double', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Дюбель','Dubbel', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Копчений','Smoked', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Коричневий','Brown', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Кьольш','Kölsch', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Оуд','Oud', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Сайзон','Saison', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Сейзон','Saison', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Трипель','Tripel', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Тріпель','Tripel', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Хез','Gueuze', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Янтарний','Amber', 'uk','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Ячмінне вино','Barleywine', 'uk','BJCP_2021');

--Brewers Association
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('#bil','Barleywine', 'en','BA_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('#bil','Barleywine', 'es','BA_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('#bil','Barleywine', 'uk','BA_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Biere','Bière', 'es','BA_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Biere','Bière', 'es','BA_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Biere','Bière', 'es','BA_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Kolsch','Koelsch', 'en','BA_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Kolsch','Koelsch', 'es','BA_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Kolsch','Koelsch', 'uk','BA_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Marzen','Maerzen', 'en','BA_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Marzen','Maerzen', 'es','BA_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Marzen','Maerzen', 'uk','BA_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Pilsner','Pilsener', 'uk','BA_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Pilsner','Pilsener', 'uk','BA_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Pilsner','Pilsener', 'uk','BA_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Octoberfest','Oktoberfest', 'en','BA_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Octoberfest','Oktoberfest', 'es','BA_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Octoberfest','Oktoberfest', 'uk','BA_2021');

-- BJCP 2025 Cider English
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Aeppletreow','Æppeltreow', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Poire','Poiré', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Ecologiques','Écologiques', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('petillant','pétillant', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Glace','Glacé', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Sacre','Sacré', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Limon','Limón', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Montes','Montés', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Bouche','Bouché', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Cuvee','Cuvée', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('Ecusson','Écusson', 'en','BJCP_2021');
INSERT INTO SYNONYMS (left, right, language, revision) VALUES ('MLF','malolactic fermentation', 'en','BJCP_2021');

