DELETE FROM SYNONYMS;

INSERT INTO SYNONYMS (left,right, language) VALUES ('Altenmunster','Altenmünster', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Biere','Bière', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('#bil','Barleywine', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Brau','Bräu', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Burgerbrau','Bürgerbräu', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Dollnitzer','Döllnitzer', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Dusseldorf','Düsseldorf', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Fruh','Früh', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Fuchschen','Füchschen', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Gratzer','Grätzer', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Hazy IPA','New England IPA', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Hefeweizen','Weissbier', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Lowenbrau','Löwenbraü', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Kolsch','Kölsch', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Koln','Köln', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Konig','König', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Kostritzer','Köstritzer', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Marzen','Märzen', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Monchshof','Mönchshof', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Muhlen','Mühlen', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Munchner','Münchner', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Naturtrub','Naturtrüb', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('New England IPA','New England IPA', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Octoberfest','Märzen', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Oktoberfest','Märzen', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Naturtrub','Naturtrüb', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Schlosser','Schlösser', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Schlussel','Schlüssel', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Schonramer','Schönramer', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Sunner','Sünner', 'en');
INSERT INTO SYNONYMS (left,right, language) VALUES ('Troegs','Tröegs', 'en');
